version: "3.7"
services:
    main:
        build: wgbot/
        volumes:
            - ./wgbot/:/opt/WGBOT
        restart: always
        ports: 
            - 80:80
        command: bash -c "pip3 install -r requirements.txt && python3 main.py"
    vk:
        build: wgbot/
        volumes:
            - ./wgbot/:/opt/WGBOT
        restart: always
        ports: 
            - 443:443
        command: bash -c "pip3 install -r requirements.txt && python3 VK.py"

 
        
